# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload_key',
            field=models.CharField(default='dnv9a68OSGG469zW1GKrlw==', max_length=26),
        ),
    ]
