# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='generated_filename',
            field=models.CharField(default='8z2khh0j', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='upload_key',
            field=models.CharField(default='Ms13qMogR/GLkS0Tofo0Qw==', max_length=26),
        ),
    ]
