# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0002_auto_20190213_1244'),
        ('backendAPI', '0002_auto_20190213_0253'),
    ]

    operations = [
    ]
