# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0003_merge_20190213_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='generated_filename',
            field=models.CharField(default='cv0sc9rb', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='upload_key',
            field=models.CharField(default='t0AjrBYOT/S7AVq1sn59TQ', max_length=26),
        ),
    ]
