# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-13 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0004_auto_20190213_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='generated_filename',
            field=models.CharField(default='7vgi34yq', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='upload_key',
            field=models.CharField(default='ntT0W6QgSv2aYn6PqrSpXA', max_length=26),
        ),
    ]
